### ISSUE TITLE
Regarding Security

### ISSUE THREAD

**Issue by fattysun1121** [aruizs/unleash-client-cpp#37]
Hello developers!

First of all, thanks for the hard work. The SDK seems to satisfy all our requirements, so we are interested in integrating this SDK to our enterprise application. Is there any known security issues?

**Comment by aruizs** [comment]
Hello,

There is no any known security issues for now. If you find any of them, please report it.

Thanks!

**Comment by fattysun1121** [comment]
Ok great, thanks.
